INSERT INTO test.customers (id, name) VALUES (1, 'Jack');
INSERT INTO test.customers (id, name) VALUES (2, 'Piter');
INSERT INTO test.customers (id, name) VALUES (3, 'John');
INSERT INTO test.customers (id, name) VALUES (4, 'Goodwin');
INSERT INTO test.customers (id, name) VALUES (5, 'Bruce');
INSERT INTO test.customers (id, name) VALUES (6, 'Levon');
INSERT INTO test.customers (id, name) VALUES (7, 'Gevorg');
INSERT INTO test.customers (id, name) VALUES (8, 'Anthony');
INSERT INTO test.customers (id, name) VALUES (9, 'Vilat');
